/**
 * Source registry — Section 10.
 *
 * Every entry here is a real, publicly documented feed. Nothing is invented.
 * `publisher_group` powers source-independence checks (Section 13): two feeds
 * sharing a group are NOT counted as independent confirmation.
 */
export interface SourceDef {
  id: string;
  name: string;
  homepage_url: string;
  feed_url: string;
  kind: 'rss' | 'geojson';
  origin_type: 'official' | 'scientific' | 'agency' | 'outlet';
  country: string | null;
  language: string;
  categories: string;
  publisher_group: string;
  /** 0..100, with a written basis. Absent = not assessed, treated as unknown. */
  reliability_score?: number;
  reliability_basis?: string;
}

export const SOURCES: SourceDef[] = [
  {
    id: 'usgs-quakes',
    name: 'USGS Earthquake Hazards Program',
    homepage_url: 'https://earthquake.usgs.gov/',
    feed_url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson',
    kind: 'geojson',
    origin_type: 'scientific',
    country: 'US',
    language: 'en',
    categories: 'natural_events',
    publisher_group: 'usgs',
    reliability_score: 98,
    reliability_basis: 'Primary instrumental measurement authority; publishes machine-readable magnitude/depth/coordinates with revision history.',
  },
  {
    id: 'noaa-tsunami',
    name: 'NOAA / NWS Tsunami Warning Center',
    homepage_url: 'https://www.tsunami.gov/',
    feed_url: 'https://www.tsunami.gov/events/xml/PAAQAtom.xml',
    kind: 'rss',
    origin_type: 'official',
    country: 'US',
    language: 'en',
    categories: 'natural_events',
    publisher_group: 'noaa',
    reliability_score: 97,
    reliability_basis: 'Official warning authority for the Pacific basin.',
  },
  {
    id: 'bbc-world',
    name: 'BBC News — World',
    homepage_url: 'https://www.bbc.com/news/world',
    feed_url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    kind: 'rss',
    origin_type: 'outlet',
    country: 'GB',
    language: 'en',
    categories: 'general_news,politics,war_conflict',
    publisher_group: 'bbc',
    reliability_score: 88,
    reliability_basis: 'Editorial standards body, published corrections policy, own newsgathering.',
  },
  {
    id: 'bbc-technology',
    name: 'BBC News — Technology',
    homepage_url: 'https://www.bbc.com/news/technology',
    feed_url: 'https://feeds.bbci.co.uk/news/technology/rss.xml',
    kind: 'rss',
    origin_type: 'outlet',
    country: 'GB',
    language: 'en',
    categories: 'technology,ai',
    publisher_group: 'bbc',
    reliability_score: 88,
    reliability_basis: 'Same editorial standards as BBC World; same publisher group (not independent from it).',
  },
  {
    id: 'guardian-world',
    name: 'The Guardian — World',
    homepage_url: 'https://www.theguardian.com/world',
    feed_url: 'https://www.theguardian.com/world/rss',
    kind: 'rss',
    origin_type: 'outlet',
    country: 'GB',
    language: 'en',
    categories: 'general_news,politics,environment',
    publisher_group: 'guardian',
    reliability_score: 85,
    reliability_basis: 'Own newsgathering, published corrections column.',
  },
  {
    id: 'publico-geral',
    name: 'Público',
    homepage_url: 'https://www.publico.pt/',
    feed_url: 'https://feeds.feedburner.com/PublicoRSS',
    kind: 'rss',
    origin_type: 'outlet',
    country: 'PT',
    language: 'pt-PT',
    categories: 'general_news,politics,society',
    publisher_group: 'publico',
    reliability_score: 84,
    reliability_basis: 'Portuguese daily with own newsroom; ERC-regulated.',
  },
  {
    id: 'rtp-noticias',
    name: 'RTP Notícias',
    homepage_url: 'https://www.rtp.pt/noticias/',
    feed_url: 'https://www.rtp.pt/noticias/rss',
    kind: 'rss',
    origin_type: 'outlet',
    country: 'PT',
    language: 'pt-PT',
    categories: 'general_news,politics,society',
    publisher_group: 'rtp',
    reliability_score: 85,
    reliability_basis: 'Portuguese public broadcaster with own newsroom; ERC-regulated.',
  },
  {
    id: 'observador',
    name: 'Observador',
    homepage_url: 'https://observador.pt/',
    feed_url: 'https://observador.pt/feed/',
    kind: 'rss',
    origin_type: 'outlet',
    country: 'PT',
    language: 'pt-PT',
    categories: 'general_news,politics,economy',
    publisher_group: 'observador',
    reliability_score: 78,
    reliability_basis: 'Portuguese digital outlet with own newsroom; carries opinion alongside reporting, so claims need separating.',
  },
  {
    id: 'gdacs',
    name: 'GDACS — Global Disaster Alert and Coordination System',
    homepage_url: 'https://www.gdacs.org/',
    feed_url: 'https://www.gdacs.org/xml/rss.xml',
    kind: 'rss',
    origin_type: 'official',
    country: 'INT',
    language: 'en',
    categories: 'natural_events',
    publisher_group: 'gdacs',
    reliability_score: 96,
    reliability_basis: 'Joint UN / European Commission alert system aggregating official hazard data (earthquake, cyclone, flood, volcano).',
  },
  {
    id: 'nasa-breaking',
    name: 'NASA — Breaking News',
    homepage_url: 'https://www.nasa.gov/',
    feed_url: 'https://www.nasa.gov/news-release/feed/',
    kind: 'rss',
    origin_type: 'official',
    country: 'US',
    language: 'en',
    categories: 'space,science',
    publisher_group: 'nasa',
    reliability_score: 96,
    reliability_basis: 'Primary agency announcements about its own missions.',
  },
  {
    id: 'esa-news',
    name: 'European Space Agency',
    homepage_url: 'https://www.esa.int/',
    feed_url: 'https://www.esa.int/rssfeed/Our_Activities/Space_News',
    kind: 'rss',
    origin_type: 'official',
    country: 'EU',
    language: 'en',
    categories: 'space,science',
    publisher_group: 'esa',
    reliability_score: 95,
    reliability_basis: 'Primary agency announcements about its own missions.',
  },
  {
    id: 'who-dons',
    name: 'WHO — Disease Outbreak News',
    homepage_url: 'https://www.who.int/emergencies/disease-outbreak-news',
    feed_url: 'https://www.who.int/rss-feeds/news-english.xml',
    kind: 'rss',
    origin_type: 'official',
    country: 'INT',
    language: 'en',
    categories: 'health',
    publisher_group: 'who',
    reliability_score: 93,
    reliability_basis: 'Intergovernmental health authority; outbreak notifications are primary records.',
  },
  {
    id: 'ecb-press',
    name: 'European Central Bank — Press',
    homepage_url: 'https://www.ecb.europa.eu/',
    feed_url: 'https://www.ecb.europa.eu/rss/press.html',
    kind: 'rss',
    origin_type: 'official',
    country: 'EU',
    language: 'en',
    categories: 'economy,finance',
    publisher_group: 'ecb',
    reliability_score: 97,
    reliability_basis: 'Primary source for euro-area monetary policy decisions.',
  },
  {
    id: 'arxiv-cs-ai',
    name: 'arXiv cs.AI',
    homepage_url: 'https://arxiv.org/list/cs.AI/recent',
    // Note: arXiv publishes no items on weekends (skipDays). An empty feed is
    // reported as 'degraded', never backfilled with invented entries.
    feed_url: 'https://rss.arxiv.org/rss/cs.AI',
    kind: 'rss',
    origin_type: 'scientific',
    country: 'INT',
    language: 'en',
    categories: 'ai,science',
    publisher_group: 'arxiv',
    reliability_score: 70,
    reliability_basis: 'Preprint server: authentic record of submission, but NOT peer reviewed. Claims must be labelled as preprint.',
  },
];
